### PR TITLE
MOTR-166 NPM Security Updates

### PR DESCRIPTION
**Pull request by jimmyzhen**
**Key Changes:**
1. Updated all outdated modules to address audited vulnerabilities.
2. Removed `babel` dependencies since `@babel/core` is included in `create-react-app`.
3. Added rule in eslint config file to suppress warning about using `storybook` as devDependencies.
4. Replaced the Circle CI Docker image `circleci/node:10.12-browsers` with `circleci/node:10.13-browsers` in the Circle CI `config.yml` file due to `Eslint@6.6.0` incompatibility with the currently used image.

### CODE REVIEW

**Comment by kilodalton** [comment]
@jimmyzhen it appears we have a few dependencies that are not used.

Unused `devDependencies`:
* react-test-renderer
* stylelint
* stylelint-config-recommended


Can you double check those? If they are not being used this is a good time to remove them.


Also I am seeing these errors reported by eslint for `releaseEntry.jsx`:

image

**Comment by jimmyzhen** [comment]
`react-test-renderer` is a dependency for `enzyme-adapter-react-16`. But since it is included in the `enzyme-adapter-react-16` specified in the `devDependencies`, I have removed `react-test-renderer` from the `devDependencies` in the `package.json`. 

After that, I did a clean install of the `npm` modules. The tests were run without errors.

**Comment by jimmyzhen** [comment]
In regards to the `stylelint` dependency, it appears to be a useful tool although it hasn't been obvious as to how it's been used in the app.

So I have added `"sass-lint": "stylelint --config=stylelint.config.js '**/*.scss'"` in the `package.json` so that we can simply run `yarn sass-lint` in **Terminal** and it will output the linting results.

**Comment by jimmyzhen** [comment]
In regards to the `eslint` warnings for the `releaseEntry.jsx` file, things checked by the `arrow-body-style` and `no-console` lintings are useful for code readability and/or debugging.

Nevertheless, I refactored the syntaxes a bit in the file to address the linting warnings.

Similar warnings are also present in other files of the app. I will refactor those as I come across them.

**Comment by kilodalton** [comment]
Merged MOTR-166

**Pull request merged**
